### ISSUE TITLE
Display Events

### ISSUE THREAD

**Issue by matthewaustinbell** [nss-evening-cohort-9/nutshell-almond#12]
# User Story
As a user, when I go to the Events page, I should see my saved events .

# Acceptance Criteria
GIVEN a user has saved events
WHEN the user visits their dashboard
THEN the events should be presented in the Events component
AND the user should only see articles that belong to their uid.

# Dev Notes
* create div in index with id of `events` - this is to show/hide page
* inside this div - make 2 more each with `col-6` (2 column) one with id of `my-events`, the other with id of `create-event`
* Create 2 files -  `javascripts/components/events.scss`, `javascripts/helpers/eventsData.js`
* In`eventsData` file make a function called `getEventsByUid`.  It should be an axios call to `${firebaseUrl}/events.json?orderBy="uid"&equalTo="${uid}"`.  This should return an array of events - with ids in them.
* In the `init` function inside  `events.js` file import `eventsData` and call that function.  
* pass array to domStringBuilder, and then `printToDom` - `util.printToDom('my-events', domString)`

**Comment by matthewaustinbell** [comment]
# User Story
As a user, I should be able to enter in an event that will happen at a future date and see all my events.

# Acceptance Criteria
# CREATE
GIVEN a user wants to keep track on a future event
WHEN the user clicks an affordance to enter a new event in the application
THEN a form should be presented to the user in which the following properties of the event can be provided

Name of event
Date of event
Location of event
GIVEN a user has entered in all details of an event
WHEN the user performs a gesture to save the event
THEN the event should be displayed in the application in the Events component

# READ
GIVEN a user has saved events
WHEN the user visits their dashboard
THEN the events should be presented in the Events component
AND the user should only see articles that belong to their uid.

# UPDATE
GIVEN a user wants to change the details of an event
WHEN the user performs a gesture to edit an event
THEN the user should be presented with a form that has the event details pre-filled into the fields
AND there should be an affordance to save the new details

# DELETE
GIVEN a user wants to delete an event
WHEN the user clicks a delete affordance
THEN the event is removed from firebase and no longer displays in the event component

**Comment by Dev-Davis** [comment]
<img width="800" alt="events_wireframe" src="https://user-images.githubusercontent.com/24858089/59073752-13c63080-888e-11e9-9c94-b08b21bde81a.png">
