### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by matthewaustinbell** [nss-evening-cohort-9/nutshell-almond#14]
# User Story
As a user, I should see a stable home page upon page load

# AC
**ONCE** the page has loaded
**THERE** will be 3 clickable sections
**AND** one should say "News"
**AND** one should say "Diary"
**AND** one should say "Events"
**AND** when a button is clicked I should go to the correct page and I should see a console.error

# Developer
* Go to the `index.html`
* create a div with and id =`home`
* Inside that div there should be 3 clickable buttons - News, Diary, Events
* Add event listeners to each button (in main.js) - when a button is clicked, the home page should be hidden, the page from the button should be shown and i should see a console.error that says the page name
* Create 3 components - `javascripts/components/news`, `javascripts/components/events`, `javascripts/components/diary`
* inside each component should be a js file.
* inside each js file should be an `init` function
* the `init` function should be exported and should contain a `console.error` of the page name

**Comment by Dev-Davis** [comment]
<img width="788" alt="Screen Shot 2019-06-04 at 8 30 48 PM" src="https://user-images.githubusercontent.com/24858089/59072886-28082e80-888a-11e9-81ea-6acd5b726943.png">
