### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Dev-Davis** [nss-evening-cohort-9/nutshell-almond#16]
h1. User Story
As a user, when the page loads, I should see a navbar.

h1. AC
**WHEN** the page loads
**THEN** I should see and navbar
**AND** if I am logged in, I should see a brand logo and links for events, news, diary, and logout
**AND** if I am logged out, I should see a brand logo and a link for authentication

h1. Dev Notes
* use bootstrap navbar - put the code in index.html, put an id on each a tag
* Make a MyNavbar.js component - Add logic for logout, add logic for clicking any of the other buttons (show the correct div)
* In the `authData` file add or remove `.hide` for each navbar link

**Comment by Dev-Davis** [comment]
<img width="578" alt="diary_wireframe" src="https://user-images.githubusercontent.com/24858089/59073371-7caca900-888c-11e9-9fda-1100799cb80b.png">

**Comment by zoeames** [comment]
This ticket can't be done until #8 is done
